### ISSUE TITLE
Missing Target Directory Contao 4.9.2

### ISSUE THREAD

**Issue by Ainschy** [bwein-net/contao-backend-customizer#1]
Hi, ich try your extension and it's look very nice.

by following the readme i become an issue from the console

> vendor/bin/contao-console assets:install --symlink --relative
>  [OK] Stylesheet for Backend Customizer was generated.
> xx:xx:xx ERROR     [console] Error thrown while running command "assets:install --symlink --relative". Message: "The target directory "" does not exist." ["exception" => Symfony\Component\Console\Exception\InvalidArgumentException^ { …},"command" => "assets:install --symlink --relative","message" => "The target directory "" does not exist."]
> 
>   The target directory "" does not exist.

**Comment by rabauss** [comment]
Well, in Symfony 4 the target directory for `assets:install` is required. I updated the Readme ;-)

see: https://github.com/bwein-net/contao-backend-customizer/commit/fd7597a0c0aa7bafbe7da8e7f9d7c77a07d42234
