### ISSUE TITLE
Wenn sich in der config.yml ein Minuszeichen im header_title String befindet gibt es eine ParseError Fehlermeldung

### ISSUE THREAD

**Issue by kreadiv** [bwein-net/contao-backend-customizer#2]
Beispiel:

bwein_backend_customizer:
  header_title: 'max-mustermann.de'
  header_color: ''

Fehlermeldung:

` [WARNING] Stylesheet for Backend Customizer could not be generated: "ParseError: Unexpected input on line 1, column 01| @headerTitle: max-mustermann.de;@headerColor: null;@envTitle: local;@envColor: null;"`

**Comment by rabauss** [comment]
Ja, das ist leider ein Problem mit der aktuellen LESS-Lösung.
Ich wollte die Erweiterung aber sowieso die nächsten Tage etwas überarbeiten und auch Kompatibilität zu Contao 4.11 herstellen bzw. paar Ideen von https://github.com/contao/contao/pull/1999 übernehmen ;-)

**Comment by kreadiv** [comment]
Ist ja nicht so wichtig. Auf jeden Fall eine sehr schön umgesetzte und praktische Erweiterung! Danke :-)

**Comment by rabauss** [comment]
Ich werde versuchen von LESS auf CSS-Variablen umzubauen. Dann habe ich zwar keinen IE11-Support mehr. Aber das ist glaube ich vernachlässigbar und die Einstellungen werden ohne Neu-Generierung übernommen!

**Comment by rabauss** [comment]
Ist gefixt mit der neuesten Version :-)
